#!/bin/sh

echo "Crating user's home directories"
mkdir -p docs downloads media/{pics,videos}
echo "Done!"

os=$(cat /etc/os-release | grep "^ID=" | cut -d "=" -f 2)
if [ "$os" = "arch" ]; then
	echo "Make sure nice-to-have packages are installed"
	sudo pacman -Syu --needed pacman-contrib neovim lsd openssh
fi
