#! /bin/sh

# Make sure bspwm removes all its rules for a clean restart
bspc rule -r "*"

# --- Autostart --- #
xrdb -merge $HOME/.Xresources
numlockx on
setxkbmap us -option compose:ralt

# Reload screens
"$HOME"/.config/dotscripts/multimonitor.sh

# Set wallpaper
feh --bg-fill "$HOME/.config/bspwm/wallpaper.jpg"

# Start picom if dead
pgrep -x picom > /dev/null || picom -b &

# Start sxhkd if dead
pgrep -x sxhkd > /dev/null || sxhkd &

# Start dunst if dead
pgrep -x dunst > /dev/null || dunst &

# Start Polybar
"$HOME"/.config/dotscripts/launch-polybar.sh &

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

# --- Workspaces --- #
bspc config automatic_scheme alternate
bspc config initial_polarity second_child

# --- Windows --- #
# Colors
bspc config normal_border_color "#151515"
bspc config focused_border_color "#6285ef"
bspc config active_border_color "#252e77"
bspc config urgent_border_color "#e06c75"

bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action_3 resize_corner

bspc config click_to_focus none
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Gaps
bspc config border_width         2
bspc config window_gap          10

# Modes
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
